-- ═══════════════════════════════════════════════════════════════════
-- EDUFORMIUM — AI Questions Generator — migration 002
-- v2: NOW A NO-OP. Nothing in this file needs to run.
--
-- The original version of this migration created a separate
-- `exam_transactions` table and an `increment_exam_credits` RPC for a
-- standalone exam-credit wallet. Per explicit direction, this app now
-- shares the Lesson Planner's real wallet instead: the real
-- `transactions` table and the real `increment_coins` RPC
-- (functions/api/payment/[[path]].js) already exist in this Supabase
-- project from the Lesson Planner's own setup, and
-- functions/api/exam-payment/[[path]].js now reads/writes those directly.
-- There is nothing new for this app to create for payments.
--
-- If you already ran the OLD version of this file, `exam_transactions`
-- and `increment_exam_credits` are now unused — safe to drop once you've
-- confirmed the shared-wallet switch is live and working:
--   drop table if exists exam_transactions;
--   drop function if exists increment_exam_credits(uuid, integer);
--
-- (Rate limiting still needs no table of its own — it reads
-- exam_generations' own timestamps, created by 001_exam_tables.sql.)
-- ═══════════════════════════════════════════════════════════════════
